apiVersion: v1
data:
  alertmanager.yml: |
    global: {}
    receivers:
    - name: slack-notifications
      slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#alert'
        send_resolved: true
    route:
      group_interval: 5m
      group_wait: 10s
      receiver: slack-notifications
      repeat_interval: 3h
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: monitor
  creationTimestamp: "2021-09-15T16:06:45Z"
  labels:
    app: prometheus
    app.kubernetes.io/managed-by: Helm
    chart: prometheus-14.6.1
    component: alertmanager
    heritage: Helm
    release: prometheus
  name: prometheus-alertmanager
  namespace: monitor
  resourceVersion: "543897"
